uncached for macos

diff --git a/.github/workflows/test-1079-patch.yml b/.github/workflows/test-1079-patch.yml
--- a/.github/workflows/test-1079-patch.yml
+++ b/.github/workflows/test-1079-patch.yml
@@ -24,7 +24,7 @@ jobs:
           python-version: |
             3.13.3
             3.12.10
-            3.11.9
+            3.11.8
             3.10.17
             3.9.22
 
@@ -36,13 +36,13 @@ jobs:
           which python3
           which python3.13.3 || echo "python3.13.3 not found"
           which python3.12.10 || echo "python3.12.10 not found"
-          which python3.11.9 || echo "python3.11.9 not found"
+          which python3.11.8 || echo "python3.11.8 not found"
           which python3.10.17 || echo "python3.10.17 not found"
           which python3.9.22 || echo "python3.9.22 not found"
           command -v python || echo "python not found"
           command -v python3.13.3 || echo "python3.13.3 not found"
           command -v python3.12.10 || echo "python3.12.10 not found"
-          command -v python3.11.9 || echo "python3.11.9 not found"
+          command -v python3.11.8 || echo "python3.11.8 not found"
           command -v python3.10.17 || echo "python3.10.17 not found"
           command -v python3.9.22 || echo "python3.9.22 not found"
           echo "Python version:"
@@ -75,11 +75,11 @@ jobs:
         run: |
           python3.12.10 --version || echo "python3.12.10 not callable"
           python3.12.10 hello.py || echo "Failed to run hello.py with python3.12.10"
-      - name: Try calling python3.11.9
+      - name: Try calling python3.11.8
         shell: bash
         run: |
-          python3.11.9 --version || echo "python3.11.9 not callable"
-          python3.11.9 hello.py || echo "Failed to run hello.py with python3.11.9"
+          python3.11.8 --version || echo "python3.11.8 not callable"
+          python3.11.8 hello.py || echo "Failed to run hello.py with python3.11.8"
       - name: Try calling python3.10.17
         shell: bash
         run: |
