without sudo

diff --git a/.github/workflows/test-with-docker.yml b/.github/workflows/test-with-docker.yml
--- a/.github/workflows/test-with-docker.yml
+++ b/.github/workflows/test-with-docker.yml
@@ -35,12 +35,12 @@ jobs:
       #   run: |
       #     apt-get update
       #     apt-get install -y docker.io
-      # - name: Ensure Sudo is Installed
-      #   run: |
-      #     if ! command -v sudo &> /dev/null; then
-      #       echo "sudo could not be found. Installing..."
-      #       apt-get update && apt-get install -y sudo
-      #     fi
+      - name: Ensure Sudo is Installed
+        run: |
+          if ! command -v sudo &> /dev/null; then
+            echo "sudo could not be found. Installing..."
+            apt-get update && apt-get install -y sudo
+          fi
       - name: Install lsb-release
         run: |
           apt-get update
@@ -54,8 +54,9 @@ jobs:
       - name: fix pip issue
         run: |
             mkdir -p /github/home/.cache/pip
-            useradd -m myuser
-            chown -R myuser:myuser /github/home/.cache/pip
+            sudo useradd -m myuser
+            sudo chown -R myuser:myuser /github/home/.cache/pip
+
       #       chown -R $USER:$USER /github/home/.cache/pip
       #       chmod -R 775 /github/home/.cache/pip
       # - name: Check permissions
