uncached pathc versions

diff --git a/.github/workflows/test-1079-patch.yml b/.github/workflows/test-1079-patch.yml
--- a/.github/workflows/test-1079-patch.yml
+++ b/.github/workflows/test-1079-patch.yml
@@ -12,7 +12,7 @@ jobs:
     runs-on: ${{ matrix.os }}
     strategy:
       matrix:
-        os: [ubuntu-latest, macos-latest, windows-latest]
+        os: [ubuntu-latest, macos-latest, macos-13 windows-latest]
       fail-fast: false
 
     steps:
@@ -24,11 +24,10 @@ jobs:
           python-version: |
             3.13.2t
             3.13.1
-            3.12.1
-            3.11.1
-            3.10.1
-            3.9.1
-            3.8.1
+            3.12.8
+            3.11.8
+            3.10.10
+            3.9.12
 
       - name: Check available python executables
         shell: bash
@@ -38,19 +37,17 @@ jobs:
           which python3
           which python3.13.2t || echo "python3.13.2t not found"
           which python3.13.1 || echo "python3.13.1 not found"
-          which python3.12.1 || echo "python3.12.1 not found"
-          which python3.11.1 || echo "python3.11.1 not found"
-          which python3.10.1 || echo "python3.10.1 not found"
-          which python3.9.1 || echo "python3.9.1 not found"
-          which python3.8.1 || echo "python3.8.1 not found"
+          which python3.12.8 || echo "python3.12.8 not found"
+          which python3.11.8 || echo "python3.11.8 not found"
+          which python3.10.10 || echo "python3.10.10 not found"
+          which python3.9.12 || echo "python3.9.12 not found"
           command -v python || echo "python not found"
           python3.13.2t -VV || echo "python 3.13.2t not found"
           command -v python3.13.1 || echo "python3.13.1 not found"
-          command -v python3.12.1 || echo "python3.12.1 not found"
-          command -v python3.11.1 || echo "python3.11.1 not found"
-          command -v python3.10.1 || echo "python3.10.1 not found"
-          command -v python3.9.1 || echo "python3.9.1 not found"
-          command -v python3.8.1 || echo "python3.8.1 not found"
+          command -v python3.12.8 || echo "python3.12.8 not found"
+          command -v python3.11.8 || echo "python3.11.8 not found"
+          command -v python3.10.10 || echo "python3.10.10 not found"
+          command -v python3.9.12 || echo "python3.9.12 not found"
           echo "Python version:"
           python --version
 
@@ -63,23 +60,20 @@ jobs:
         shell: bash
         run: |
           python3.13.1 --version || echo "python3.13.1 not callable"
-      - name: Try calling python3.12.1
+      - name: Try calling python3.12.8
         shell: bash
         run: |
-          python3.12.1 --version || echo "python3.12.1 not callable"
-      - name: Try calling python3.11.1
+          python3.12.8 --version || echo "python3.12.8 not callable"
+      - name: Try calling python3.11.8
         shell: bash
         run: |
-          python3.11.1 --version || echo "python3.11.1 not callable"
-      - name: Try calling python3.10.1
+          python3.11.8 --version || echo "python3.11.8 not callable"
+      - name: Try calling python3.10.10
         shell: bash
         run: |
-          python3.10.1 --version || echo "python3.10.1 not callable"
-      - name: Try calling python3.9.1
+          python3.10.10 --version || echo "python3.10.10 not callable"
+      - name: Try calling python3.9.12
         shell: bash
         run: |
-          python3.9.1 --version || echo "python3.9.1 not callable"
-      - name: Try calling python3.8.1
-        shell: bash
-        run: |
-          python3.8.1 --version || echo "python3.8.1 not callable"
+          python3.9.12 --version || echo "python3.9.12 not callable"
+
