cached patch versions ubuntu

diff --git a/.github/workflows/test-1079-patch.yml b/.github/workflows/test-1079-patch.yml
--- a/.github/workflows/test-1079-patch.yml
+++ b/.github/workflows/test-1079-patch.yml
@@ -1,5 +1,5 @@
 # .github/workflows/test-python-versions.yml
-name: Test Python patch Versions uncached freethread
+name: Test Python patch Versions cached freethread
 
 on:
   push:
@@ -12,7 +12,7 @@ jobs:
     runs-on: ${{ matrix.os }}
     strategy:
       matrix:
-        os: [ubuntu-latest, macos-latest, macos-13, windows-latest]
+        os: [ubuntu-latest]
       fail-fast: false
 
     steps:
@@ -23,11 +23,11 @@ jobs:
         with:
           python-version: |
             3.13.2t
-            3.13.1
-            3.12.8
-            3.11.8
-            3.10.10
-            3.9.12
+            3.13.3
+            3.12.10
+            3.11.12
+            3.10.17
+            3.9.22
 
       - name: Check available python executables
         shell: bash
@@ -36,18 +36,18 @@ jobs:
           which python
           which python3
           which python3.13.2t || echo "python3.13.2t not found"
-          which python3.13.1 || echo "python3.13.1 not found"
-          which python3.12.8 || echo "python3.12.8 not found"
-          which python3.11.8 || echo "python3.11.8 not found"
-          which python3.10.10 || echo "python3.10.10 not found"
-          which python3.9.12 || echo "python3.9.12 not found"
+          which python3.13.3 || echo "python3.13.3 not found"
+          which python3.12.10 || echo "python3.12.10 not found"
+          which python3.11.12 || echo "python3.11.12 not found"
+          which python3.10.17 || echo "python3.10.17 not found"
+          which python3.9.22 || echo "python3.9.22 not found"
           command -v python || echo "python not found"
           python3.13.2t -VV || echo "python 3.13.2t not found"
-          command -v python3.13.1 || echo "python3.13.1 not found"
-          command -v python3.12.8 || echo "python3.12.8 not found"
-          command -v python3.11.8 || echo "python3.11.8 not found"
-          command -v python3.10.10 || echo "python3.10.10 not found"
-          command -v python3.9.12 || echo "python3.9.12 not found"
+          command -v python3.13.3 || echo "python3.13.3 not found"
+          command -v python3.12.10 || echo "python3.12.10 not found"
+          command -v python3.11.12 || echo "python3.11.12 not found"
+          command -v python3.10.17 || echo "python3.10.17 not found"
+          command -v python3.9.22 || echo "python3.9.22 not found"
           echo "Python version:"
           python --version
 
@@ -56,24 +56,24 @@ jobs:
         run: |
           python3.13.2t -VV || echo "python3.13.2t not callable"
 
-      - name: Try calling python3.13.1
+      - name: Try calling python3.13.3
         shell: bash
         run: |
-          python3.13.1 --version || echo "python3.13.1 not callable"
-      - name: Try calling python3.12.8
+          python3.13.3 --version || echo "python3.13.3 not callable"
+      - name: Try calling python3.12.10
         shell: bash
         run: |
-          python3.12.8 --version || echo "python3.12.8 not callable"
-      - name: Try calling python3.11.8
+          python3.12.10 --version || echo "python3.12.10 not callable"
+      - name: Try calling python3.11.12
         shell: bash
         run: |
-          python3.11.8 --version || echo "python3.11.8 not callable"
-      - name: Try calling python3.10.10
+          python3.11.12 --version || echo "python3.11.12 not callable"
+      - name: Try calling python3.10.17
         shell: bash
         run: |
-          python3.10.10 --version || echo "python3.10.10 not callable"
-      - name: Try calling python3.9.12
+          python3.10.17 --version || echo "python3.10.17 not callable"
+      - name: Try calling python3.9.22
         shell: bash
         run: |
-          python3.9.12 --version || echo "python3.9.12 not callable"
+          python3.9.22 --version || echo "python3.9.22 not callable"
 
