without sudo

diff --git a/.github/workflows/test-with-docker.yml b/.github/workflows/test-with-docker.yml
--- a/.github/workflows/test-with-docker.yml
+++ b/.github/workflows/test-with-docker.yml
@@ -20,25 +20,25 @@ jobs:
       matrix:
         python: [3.11.6]
     steps:
-      - name: Setup and prepare
-        run: |
-            sudo chown -R $(whoami):$(whoami) /__w/_temp /github/home/.cache
+      # - name: Setup and prepare
+      #   run: |
+      #       sudo chown -R $(whoami):$(whoami) /__w/_temp /github/home/.cache
       - uses: actions/checkout@v4
-        with:
-          repository: priya-kinthali/sample-python
-          token: ${{ secrets.GITHUB_TOKEN }}
-          fetch-depth: 1
+        # with:
+        #   repository: priya-kinthali/sample-python
+        #   token: ${{ secrets.GITHUB_TOKEN }}
+        #   fetch-depth: 1
 
       # - name: Install Docker
       #   run: |
       #     apt-get update
       #     apt-get install -y docker.io
-      - name: Ensure Sudo is Installed
-        run: |
-          if ! command -v sudo &> /dev/null; then
-            echo "sudo could not be found. Installing..."
-            apt-get update && apt-get install -y sudo
-          fi
+      # - name: Ensure Sudo is Installed
+      #   run: |
+      #     if ! command -v sudo &> /dev/null; then
+      #       echo "sudo could not be found. Installing..."
+      #       apt-get update && apt-get install -y sudo
+      #     fi
       - name: Install lsb-release
         run: |
           apt-get update
