repro in all os non freethreaded clear cache

diff --git a/.github/workflows/test-1079-linux.yml b/.github/workflows/test-1079-linux.yml
--- a/.github/workflows/test-1079-linux.yml
+++ b/.github/workflows/test-1079-linux.yml
@@ -25,9 +25,8 @@ jobs:
         uses: actions/setup-python@v6
         with:
           python-version: |
-            3.11
-            3.12
             3.13
+            3.14
 
       - name: Check available python executables
         shell: bash
@@ -35,25 +34,19 @@ jobs:
           echo "Checking python executables"
           which python
           which python3
-          which python3.11 || echo "python3.11 not found"
-          which python3.12 || echo "python3.12 not found"
           which python3.13 || echo "python3.13 not found"
+          which python3.14 || echo "python3.14 not found"
           command -v python || echo "python not found"
-          command -v python3.11 || echo "python3.11 not found"
-          command -v python3.12 || echo "python3.12 not found"
           command -v python3.13 || echo "python3.13 not found"
+          command -v python3.14 || echo "python3.14 not found"
           echo "Python version:"
           python --version
 
-      - name: Try calling python3.11
-        shell: bash
-        run: |
-          python3.11 --version || echo "python3.11 not callable"
-      - name: Try calling python3.12
-        shell: bash
-        run: |
-          python3.12 --version || echo "python3.12 not callable"
       - name: Try calling python3.13
         shell: bash
         run: |
           python3.13 --version || echo "python3.13 not callable"
+      - name: Try calling python3.14
+        shell: bash
+        run: |
+          python3.14 --version || echo "python3.14 not callable"
