with second pr

diff --git a/.github/workflows/test-1295.yml b/.github/workflows/test-1295.yml
--- a/.github/workflows/test-1295.yml
+++ b/.github/workflows/test-1295.yml
@@ -9,6 +9,12 @@ jobs:
       image: ubuntu:24.04
       options: --user root
     steps:
+      - name: Ensure Sudo is Installed
+        run: |
+          if ! command -v sudo &> /dev/null; then
+            echo "sudo could not be found. Installing..."
+            apt-get update && apt-get install -y sudo
+          fi
       - name: Install prerequisites
         run: |
           apt-get update
