with fix

diff --git a/.github/workflows/test-1079-final.yml b/.github/workflows/test-1079-final.yml
--- a/.github/workflows/test-1079-final.yml
+++ b/.github/workflows/test-1079-final.yml
@@ -1,9 +1,9 @@
 name: Test 1079
 
 on:
-  # push:
-  #   branches:
-  #     - test-973
+  push:
+    branches:
+      - test-973
   workflow_dispatch:
 
 jobs:
@@ -20,43 +20,59 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
+      - name: Clear existing Python versions
+        run: |
+          sudo rm -rf /Users/runner/hostedtoolcache/Python
       - name: Set up Python
-        uses: actions/setup-python@v5
+        uses: priya-kinthali/setup-python@test-1079
         with:
-          python-version: 3.8.10
-          # architecture: ${{ matrix.architecture }}
+          python-version: |
+            3.8
+            3.9
+            3.10
+            3.11
+            3.12
+            3.13
+
       - name: Check for Python 3.8.10 .exe files
         shell: cmd
         run: |
-          # echo "Checking Python 3.8.10 .exe files for architecture ${{ matrix.architecture }}..."
-          dir C:\hostedtoolcache\windows\Python\3.8.10\python-3.8.10*.exe /s /b
+          echo "Checking Python 3.8.10 .exe files for architecture ${{ matrix.architecture }}..."
+          dir C:\hostedtoolcache\windows\Python\3.8.10\*.exe /s /b
+      - name: Check available python executables
+        shell: bash
+        run: |
+          echo "Checking python executables"
+          which python
+          which python3
+          which python3.8 || echo "python3.8 not found"
+          which python3.9 || echo "python3.9 not found"
+          which python3.10 || echo "python3.10 not found"
+          which python3.11 || echo "python3.11 not found"
+          which python3.12 || echo "python3.12 not found"
+          which python3.13 || echo "python3.13 not found"
+          command -v python || echo "python not found"
+          command -v python3.8 || echo "python3.8 not found"
+          command -v python3.9 || echo "python3.9 not found"
+          command -v python3.10 || echo "python3.10 not found"
+          command -v python3.11 || echo "python3.11 not found"
+          command -v python3.12 || echo "python3.12 not found"
+          command -v python3.13 || echo "python3.13 not found"
+          echo "Python version:"
+          python --version
 
-      # - name: Check for Python 3.9.13 .exe files
-      #   shell: cmd
-      #   run: |
-      #     echo "Checking Python 3.9.13 .exe files..."
-      #     dir C:\hostedtoolcache\windows\Python\3.9.13\python-3.9.13*.exe /s /b
+      - name: Try calling python3.8
+        shell: bash
+        run: |
+          python3.8 --version || echo "python3.8 not callable"
 
-      # - name: Check for Python 3.10.11 .exe files
-      #   shell: cmd
-      #   run: |
-      #     echo "Checking Python 3.10.11 .exe files..."
-      #     dir C:\hostedtoolcache\windows\Python\3.10.11\python-3.10.11*.exe /s /b
+      - name: Try calling python3.9
+        shell: bash
+        run: |
+          python3.9 --version || echo "python3.9 not callable"
+      - name: Try calling python3.10
+        shell: bash
+        run: |
+          python3.10 --version || echo "python3.9 not callable"
 
-      # - name: Check for Python 3.11.9 .exe files
-      #   shell: cmd
-      #   run: |
-      #     echo "Checking Python 3.11.9 .exe files..."
-      #     dir C:\hostedtoolcache\windows\Python\3.11.9\python-3.11.9*.exe /s /b
-
-      # - name: Check for Python 3.12.9 .exe files
-      #   shell: cmd
-      #   run: |
-      #     echo "Checking Python 3.12.9 .exe files..."
-      #     dir C:\hostedtoolcache\windows\Python\3.12.9\python-3.12.9*.exe /s /b
-
-      # - name: Check for Python 3.13.2 .exe files
-      #   shell: cmd
-      #   run: |
-      #     echo "Checking Python 3.13.2 .exe files..."
-      #     dir C:\hostedtoolcache\windows\Python\3.13.2\python-3.13.2*.exe /s /b
+    
