windows

diff --git a/.github/workflows/test-1079-patch.yml b/.github/workflows/test-1079-patch.yml
--- a/.github/workflows/test-1079-patch.yml
+++ b/.github/workflows/test-1079-patch.yml
@@ -1,5 +1,4 @@
-# .github/workflows/test-python-versions.yml
-name: Test Python patch Versions cached 
+name: Test Python patch Versions
 
 on:
   push:
@@ -19,33 +18,24 @@ jobs:
       - uses: actions/checkout@v4
 
       - name: Setup Python
-        uses: priya-kinthali/setup-python@test-1079
+        uses: actions/setup-python@v5
         with:
           python-version: |
-            3.12.10
-            3.13.2
+            3.11.8
             3.10.11
             3.9.13
-
       - name: Check available python executables
         shell: bash
         run: |
           echo "Checking python executables"
           which python
-          which python3
-          which python3.12.10 || echo "python3.12.10 not found"
-          which python3.13.2 || echo "python3.13.2 not found"
-          which python3.10.11 || echo "python3.10.11 not found"
-          which python3.9.13 || echo "python3.9.13 not found"
-          command -v python || echo "python not found"
-          command -v python3.12.10 || echo "python3.12.10 not found"
-          command -v python3.13.2 || echo "python3.13.2 not found"
-          command -v python3.10.11 || echo "python3.10.11 not found"
-          command -v python3.9.13 || echo "python3.9.13 not found"
+          which python
+          which python3.11.8 || echo "python3.11.8 not found"
+          which python3.11 || echo "python3.11 not found"
+          command -v python3.11 || echo "python3.11 not found"
           echo "Python version:"
           python --version
           python3 --version
-          which python3.13 || echo "python3.13 not found"
       - name: Try calling python
         shell: bash
         run: |
@@ -56,36 +46,9 @@ jobs:
         run: |
           python3 --version || echo "python not callable"
           python3 hello.py || echo "Failed to run hello.py with python"
-      - name: Try calling python3.13
+      - name: Try calling python3.10
         shell: bash
         run: |
-          python3.13 --version || echo "pytho not callable"
-          python3.13 hello.py || echo "Failed to run hello.py with python3.13"
-
-      - name: Try calling python3.13.3
-        shell: bash
-        run: |
-          python3.13.3 --version || echo "python3.13.3 not callable"
-          python3.13.3 hello.py || echo "Failed to run hello.py with python3.13.3"
-      - name: Try calling python3.12.10
-        shell: bash
-        run: |
-          python3.12.10 --version || echo "python3.12.10 not callable"
-          python3.12.10 hello.py || echo "Failed to run hello.py with python3.12.10"
-      - name: Try calling python3.13.2
-        shell: bash
-        run: |
-          python3.13.2 --version || echo "python3.13.2 not callable"
-          python3.13.2 hello.py || echo "Failed to run hello.py with python3.13.2"
-      - name: Try calling python3.10.11
-        shell: bash
-        run: |
-          python3.10.11 --version || echo "python3.10.11 not callable"
-          python3.10.11 hello.py || echo "Failed to run hello.py with python3.10.11"
-      - name: Try calling python3.9.13
-        shell: bash
-        run: |
-          python3.9.13 --version || echo "python3.9.13 not callable"
-          python3.9.13 hello.py || echo "Failed to run hello.py with python3.9.13"
-
-
+          python3.10 --version || echo "python not callable"
+          python3.10 hello.py || echo "Failed to run hello.py with python3.10"
+     
