Test pythonLocation on All Runners and Implementations

diff --git a/.github/workflows/test-1138.yml b/.github/workflows/test-1138.yml
--- a/.github/workflows/test-1138.yml
+++ b/.github/workflows/test-1138.yml
@@ -32,9 +32,9 @@ jobs:
           python --version
           echo "value of pythonLocation: $pythonLocation"
           if [ "$RUNNER_OS" = "Windows" ]; then
-            echo -n "Checking Python location on Windows is" && where python.exe || echo "python.exe not found"
-            echo -n "Getting Python version from pythonLocation\\python.exe is" && $pythonLocation\\python.exe --version
+            echo -n "Checking Python location on Windows: " && where python.exe || echo "python.exe not found"
+            echo -n "Python version using pythonLocation\\python.exe is " && $pythonLocation\\python.exe --version
           else
-            echo -n "Checking Python location on Linux/Mac is" && which python || echo "python not found"
-            echo -n "Python version using pythonLocation/bin/python is" && $pythonLocation/bin/python --version
+            echo -n "Checking Python location on Linux or Mac: " && which python || echo "python not found"
+            echo -n "Python version using pythonLocation/bin/python is " && $pythonLocation/bin/python --version
           fi
