ubuntu

diff --git a/.github/workflows/test-1079-patch.yml b/.github/workflows/test-1079-patch.yml
--- a/.github/workflows/test-1079-patch.yml
+++ b/.github/workflows/test-1079-patch.yml
@@ -22,15 +22,16 @@ jobs:
         with:
           python-version: |
             3.11.8
-            3.10.11
-            3.9.13
+            3.11.7
+            3.10.17
+            3.9.22
       - name: Check available python executables
         shell: bash
         run: |
           echo "Checking python executables"
           which python
           which python
-          which python3.11.8 || echo "python3.11.8 not found"
+          which python3.9.22 || echo "python3.9.22 not found"
           which python3.11 || echo "python3.11 not found"
           command -v python3.11 || echo "python3.11 not found"
           echo "Python version:"
@@ -46,9 +47,9 @@ jobs:
         run: |
           python3 --version || echo "python not callable"
           python3 hello.py || echo "Failed to run hello.py with python"
-      - name: Try calling python3.10
+      - name: Try calling python3.11
         shell: bash
         run: |
-          python3.10 --version || echo "python not callable"
-          python3.10 hello.py || echo "Failed to run hello.py with python3.10"
+          python3.11 --version || echo "python not callable"
+          python3.11 hello.py || echo "Failed to run hello.py with python3.11"
      
