test minor versioned symlink with code changes

diff --git a/.github/workflows/test-1079-final.yml b/.github/workflows/test-1079-final.yml
--- a/.github/workflows/test-1079-final.yml
+++ b/.github/workflows/test-1079-final.yml
@@ -11,7 +11,7 @@ jobs:
     strategy:
       matrix:
         os: [windows-latest]
-        # architecture: [x86, x64]
+        architecture: [x86, x64]
 
       fail-fast: false
 
@@ -34,12 +34,7 @@ jobs:
             3.11
             3.12
             3.13
-
-      - name: Check for Python 3.8.10 .exe files
-        shell: cmd
-        run: |
-          echo "Checking Python 3.8.10 .exe files for architecture ${{ matrix.architecture }}..."
-          dir C:\hostedtoolcache\windows\Python\3.8.10\*.exe /s /b
+          architecture: ${{ matrix.architecture }}
       - name: Check available python executables
         shell: bash
         run: |
@@ -62,18 +57,40 @@ jobs:
           echo "Python version:"
           python --version
 
+      - name: Check for Python 3.8.10 .exe files
+        shell: cmd
+        run: |
+          echo "Checking Python 3.8.10 .exe files for architecture ${{ matrix.architecture }}..."
+          dir C:\hostedtoolcache\windows\Python\3.8.10\*.exe /s /b
       - name: Try calling python3.8
         shell: bash
         run: |
           python3.8 --version || echo "python3.8 not callable"
-
+          python3.8 app.py || echo "Failed to run app.py with python3.8"
       - name: Try calling python3.9
         shell: bash
         run: |
           python3.9 --version || echo "python3.9 not callable"
+          python3.9 app.py || echo "Failed to run app.py with python3.9"
       - name: Try calling python3.10
         shell: bash
         run: |
           python3.10 --version || echo "python3.9 not callable"
+          python3.10 app.py || echo "Failed to run app.py with python3.10"
+      - name: Try calling python3.11
+        shell: bash
+        run: |
+          python3.11 --version || echo "python3.11 not callable"
+          python3.11 app.py || echo "Failed to run app.py with python3.11"
+      - name: Try calling python3.12
+        shell: bash
+        run: |
+          python3.12 --version || echo "python3.12 not callable"
+          python3.12 app.py || echo "Failed to run app.py with python3.12"
+      - name: Try calling python3.13
+        shell: bash
+        run: |
+          python3.13 --version || echo "python3.13 not callable"
+          python3.13 app.py || echo "Failed to run app.py with python3.13"
 
     
