test 1309

diff --git a/.github/workflows/test-1309.yml b/.github/workflows/test-1309.yml
--- a/.github/workflows/test-1309.yml
+++ b/.github/workflows/test-1309.yml
@@ -54,6 +54,23 @@ jobs:
 
       - uses: actions/checkout@v6
 
+      - name: Ensure Sudo is Installed
+        run: |
+          if ! command -v sudo &> /dev/null; then
+            echo "sudo could not be found. Installing..."
+            apt-get update && apt-get install -y sudo
+          fi
+      # - name: Install lsb-release
+      #   run: |
+      #     apt-get update
+      #     apt-get install -y lsb-release
+      # - name: Create /etc/lsb-release
+      #   run: |
+      #     echo "DISTRIB_RELEASE=22.04" | tee -a /etc/lsb-release
+      - name: Install Docker
+        run: |
+          apt-get update
+          apt-get install -y docker.io
       - uses: actions/setup-python@v6
         with:
           python-version: '3.13'
