repro in all os

diff --git a/.github/workflows/test-1079-linux.yml b/.github/workflows/test-1079-linux.yml
--- a/.github/workflows/test-1079-linux.yml
+++ b/.github/workflows/test-1079-linux.yml
@@ -2,9 +2,9 @@
 name: Test Python Minor Versions
 
 on:
-  # push:
-  #   branches:
-  #     - test-973
+  push:
+    branches:
+      - test-973
   workflow_dispatch:
 
 jobs:
@@ -12,16 +12,17 @@ jobs:
     runs-on: ${{ matrix.os }}
     strategy:
       matrix:
-        os: [ubuntu-latest, macos-latest, windows-latest]
+        os: [ubuntu-latest, macos-latest, windows-latest, windows-11-arm, macos-15-intel, ubuntu-22.04-arm]
 
     steps:
-      - uses: actions/checkout@v4
+      - uses: actions/checkout@v6
 
-      - name: Setup Python 3.9 and 3.13
-        uses: actions/setup-python@v5
+      - name: Setup Python
+        uses: actions/setup-python@v6
         with:
           python-version: |
             3.9
+            3.10
             3.13
 
       - name: Check available python executables
@@ -31,9 +32,11 @@ jobs:
           which python
           which python3
           which python3.9 || echo "python3.9 not found"
+          which python3.10 || echo "python3.10 not found"
           which python3.13 || echo "python3.13 not found"
           command -v python || echo "python not found"
           command -v python3.9 || echo "python3.9 not found"
+          command -v python3.10 || echo "python3.10 not found"
           command -v python3.13 || echo "python3.13 not found"
           echo "Python version:"
           python --version
@@ -42,7 +45,10 @@ jobs:
         shell: bash
         run: |
           python3.9 --version || echo "python3.9 not callable"
-
+      - name: Try calling python3.10
+        shell: bash
+        run: |
+          python3.10 --version || echo "python3.10 not callable"
       - name: Try calling python3.13
         shell: bash
         run: |
