uncached for windows

diff --git a/.github/workflows/test-1079-patch.yml b/.github/workflows/test-1079-patch.yml
--- a/.github/workflows/test-1079-patch.yml
+++ b/.github/workflows/test-1079-patch.yml
@@ -12,21 +12,21 @@ jobs:
     runs-on: ${{ matrix.os }}
     strategy:
       matrix:
-        os: [macos-13]
+        os: [windows-latest]
       fail-fast: false
 
     steps:
       - uses: actions/checkout@v4
 
       - name: Setup Python
-        uses: actions/setup-python@v5
+        uses: priya-kinthali/setup-python@test-1079
         with:
           python-version: |
             3.13.3
             3.12.10
             3.11.8
-            3.10.17
-            3.9.22
+            3.10.11
+            3.9.13
 
       - name: Check available python executables
         shell: bash
@@ -37,14 +37,14 @@ jobs:
           which python3.13.3 || echo "python3.13.3 not found"
           which python3.12.10 || echo "python3.12.10 not found"
           which python3.11.8 || echo "python3.11.8 not found"
-          which python3.10.17 || echo "python3.10.17 not found"
-          which python3.9.22 || echo "python3.9.22 not found"
+          which python3.10.11 || echo "python3.10.11 not found"
+          which python3.9.13 || echo "python3.9.13 not found"
           command -v python || echo "python not found"
           command -v python3.13.3 || echo "python3.13.3 not found"
           command -v python3.12.10 || echo "python3.12.10 not found"
           command -v python3.11.8 || echo "python3.11.8 not found"
-          command -v python3.10.17 || echo "python3.10.17 not found"
-          command -v python3.9.22 || echo "python3.9.22 not found"
+          command -v python3.10.11 || echo "python3.10.11 not found"
+          command -v python3.9.13 || echo "python3.9.13 not found"
           echo "Python version:"
           python --version
           python3 --version
@@ -80,15 +80,15 @@ jobs:
         run: |
           python3.11.8 --version || echo "python3.11.8 not callable"
           python3.11.8 hello.py || echo "Failed to run hello.py with python3.11.8"
-      - name: Try calling python3.10.17
+      - name: Try calling python3.10.11
         shell: bash
         run: |
-          python3.10.17 --version || echo "python3.10.17 not callable"
-          python3.10.17 hello.py || echo "Failed to run hello.py with python3.10.17"
-      - name: Try calling python3.9.22
+          python3.10.11 --version || echo "python3.10.11 not callable"
+          python3.10.11 hello.py || echo "Failed to run hello.py with python3.10.11"
+      - name: Try calling python3.9.13
         shell: bash
         run: |
-          python3.9.22 --version || echo "python3.9.22 not callable"
-          python3.9.22 hello.py || echo "Failed to run hello.py with python3.9.22"
+          python3.9.13 --version || echo "python3.9.13 not callable"
+          python3.9.13 hello.py || echo "Failed to run hello.py with python3.9.13"
 
 
